### ISSUE TITLE
Deploying 3rd party jars

### ISSUE THREAD

**Issue by gnoymmij** [synergian/wagon-git#29]
Hi,

I followed the guide here: http://synergian.github.io/wagon-git/installation.html to deploy a 3rd party jar but received the following exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.codehaus.plexus.util.xml.pull.MXParser.<init>(Lorg/codehaus/plexus/util/xml/pull/EntityReplacementMap;)V
	at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:523)
	at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:557)
	at org.apache.maven.settings.io.DefaultSettingsReader.read(DefaultSettingsReader.java:92)
	at org.apache.maven.settings.building.DefaultSettingsBuilder.readSettings(DefaultSettingsBuilder.java:169)
	at org.apache.maven.settings.building.DefaultSettingsBuilder.build(DefaultSettingsBuilder.java:91)
	at org.apache.maven.cli.MavenCli.settings(MavenCli.java:766)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:209)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
mvn_deploy.sh: line 7: -Durl=git:releases://git@bitbucket.org:my-repo-url.git: No such file or directory
```
I have included the 0.2.3 shaded jar in $M2_HOME/lib.
Any ideas?

**Comment by mschonaker** [comment]
For the record. I had this problem when added wagon-git jar among the Maven libs.

**Comment by mschonaker** [comment]
Got it working for Maven 3.2.2 by updating some dependencies. Try with version 0.2.5.
