### ISSUE TITLE
Cannot deploy jar on Bitbucket

### ISSUE THREAD

**Issue by AndyKitezh** [synergian/wagon-git#30]
I try to  deploy jar on Bitbucket repo, but during excecuting deploying script, I entered password to repo 4 times, also I've got next error:

[DEBUG] RAN: git commit --allow-empty -m [wagon-git] commit to branch site 1/21/15 4:30 PM / $? = 128
 Session error: org.apache.maven.wagon.ConnectionException: Unable to push git repostory: Unable to commit files
 Session error: org.apache.maven.wagon.ConnectionException: Unable to push git repostory: Unable to commit files
[ERROR] Error disconnecting wagon - ignored
org.apache.maven.wagon.ConnectionException: Unable to push git repostory: Unable to commit files
	at ar.com.synergian.wagongit.GitWagon.closeConnection(GitWagon.java:122)
	at org.apache.maven.wagon.AbstractWagon.disconnect(AbstractWagon.java:232)
	at org.apache.maven.plugins.site.AbstractDeployMojo.deploy(AbstractDeployMojo.java:332)
	at org.apache.maven.plugins.site.AbstractDeployMojo.deployTo(AbstractDeployMojo.java:281)
	at org.apache.maven.plugins.site.AbstractDeployMojo.execute(AbstractDeployMojo.java:163)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: ar.com.synergian.wagongit.GitException: Unable to commit files
	at ar.com.synergian.wagongit.GitBackend.pushAll(GitBackend.java:174)
	at ar.com.synergian.wagongit.GitWagon.closeConnection(GitWagon.java:116)
	... 25 more

Using this script:
mvn clean deploy site-deploy -DperformRelease -Dwagon.git.debug=true

**Comment by mschonaker** [comment]
This looks like a git problem. Git is unable to commit. Maybe some pending changes?
